<a href="https://colab.research.google.com/github/Skan90/PythonData/blob/main/Projeto_Emprego.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 1000)
#pd.set_option('display.max_rows', 1000)

In [ ]:
tabela = pd.read_excel("Produtos.xlsx", )
display(tabela)

,EAN,Descrição,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Preço,Info
0,7891010504779,BAND-AID TRANSP 10UN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7891010504755,BAND-AID TRANSP 40UN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7891010668631,BAND-AID ULTRAPROT 24X15 UN BIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7891010576509,CAREFREE PROTECAO C/PERFUME 80UN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7891010015268,CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
83,7891010026264,SUNDOWN KIDS FPS 60 SKYLINE 120ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,7896212479924,TYLENOL 200MG GOTAS 15ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,7891010249274,TYLENOL 750MG BLISTER C/4 CP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,7896212422517,TYLENOL 750MG CARTUCHO C/ 20CP,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,7896212428861,TYLENOL BEBE GOTAS 15ML,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(tabela)

              EAN                              Descrição  Unnamed: 2  \
0   7891010504779                   BAND-AID TRANSP 10UN         NaN
1   7891010504755                   BAND-AID TRANSP 40UN         NaN
2   7891010668631        BAND-AID ULTRAPROT 24X15 UN BIL         NaN
3   7891010576509       CAREFREE PROTECAO C/PERFUME 80UN         NaN
4   7891010015268  CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN         NaN
..            ...                                    ...         ...
83  7891010026264      SUNDOWN KIDS FPS 60 SKYLINE 120ML         NaN
84  7896212479924               TYLENOL 200MG GOTAS 15ML         NaN
85  7891010249274           TYLENOL 750MG BLISTER C/4 CP         NaN
86  7896212422517         TYLENOL 750MG CARTUCHO C/ 20CP         NaN
87  7896212428861                TYLENOL BEBE GOTAS 15ML         NaN

    Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Preço  Info
0          NaN         NaN         NaN         NaN    NaN   NaN
1          NaN         NaN         NaN         NaN    NaN   NaN
2          NaN         NaN         NaN         NaN    NaN   NaN
3          NaN         NaN         NaN         NaN    NaN   NaN
4          NaN         NaN         NaN         NaN    NaN   NaN
..         ...         ...         ...         ...    ...   ...
83         NaN         NaN         NaN         NaN    NaN   NaN
84         NaN         NaN         NaN         NaN    NaN   NaN
85         NaN         NaN         NaN         NaN    NaN   NaN
86         NaN         NaN         NaN         NaN    NaN   NaN
87         NaN         NaN         NaN         NaN    NaN   NaN

[88 rows x 9 columns]

In [ ]:
tabela.drop('Unnamed: 2',axis=1, inplace=True)

In [ ]:
display(tabela)

,EAN,Descrição,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Preço,Info
0,7891010504779,BAND-AID TRANSP 10UN,NaN,NaN,NaN,NaN,NaN,NaN
1,7891010504755,BAND-AID TRANSP 40UN,NaN,NaN,NaN,NaN,NaN,NaN
2,7891010668631,BAND-AID ULTRAPROT 24X15 UN BIL,NaN,NaN,NaN,NaN,NaN,NaN
3,7891010576509,CAREFREE PROTECAO C/PERFUME 80UN,NaN,NaN,NaN,NaN,NaN,NaN
4,7891010015268,CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
83,7891010026264,SUNDOWN KIDS FPS 60 SKYLINE 120ML,NaN,NaN,NaN,NaN,NaN,NaN
84,7896212479924,TYLENOL 200MG GOTAS 15ML,NaN,NaN,NaN,NaN,NaN,NaN
85,7891010249274,TYLENOL 750MG BLISTER C/4 CP,NaN,NaN,NaN,NaN,NaN,NaN
86,7896212422517,TYLENOL 750MG CARTUCHO C/ 20CP,NaN,NaN,NaN,NaN,NaN,NaN
87,7896212428861,TYLENOL BEBE GOTAS 15ML,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
tabela.drop('Unnamed: 3',axis=1, inplace=True)

In [ ]:
tabela.drop('Unnamed: 4',axis=1, inplace=True)

In [ ]:
tabela.drop('Unnamed: 5',axis=1, inplace=True)
tabela.drop('Unnamed: 6',axis=1, inplace=True)

In [ ]:
display(tabela)

              EAN                              Descrição  Preço  Info
0   7891010504779                   BAND-AID TRANSP 10UN    NaN   NaN
1   7891010504755                   BAND-AID TRANSP 40UN    NaN   NaN
2   7891010668631        BAND-AID ULTRAPROT 24X15 UN BIL    NaN   NaN
3   7891010576509       CAREFREE PROTECAO C/PERFUME 80UN    NaN   NaN
4   7891010015268  CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN    NaN   NaN
..            ...                                    ...    ...   ...
83  7891010026264      SUNDOWN KIDS FPS 60 SKYLINE 120ML    NaN   NaN
84  7896212479924               TYLENOL 200MG GOTAS 15ML    NaN   NaN
85  7891010249274           TYLENOL 750MG BLISTER C/4 CP    NaN   NaN
86  7896212422517         TYLENOL 750MG CARTUCHO C/ 20CP    NaN   NaN
87  7896212428861                TYLENOL BEBE GOTAS 15ML    NaN   NaN

[88 rows x 4 columns]

In [ ]:
tabela["Preço"] = 0

In [ ]:
tabela.rename({'Info':'Estoque em Loja'}, axis=1, inplace=True)

In [ ]:
display(tabela)

,EAN,Descrição,Preço,Estoque em Loja
0,7891010504779,BAND-AID TRANSP 10UN,0,NaN
1,7891010504755,BAND-AID TRANSP 40UN,0,NaN
2,7891010668631,BAND-AID ULTRAPROT 24X15 UN BIL,0,NaN
3,7891010576509,CAREFREE PROTECAO C/PERFUME 80UN,0,NaN
4,7891010015268,CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN,0,NaN
...,...,...,...,...
83,7891010026264,SUNDOWN KIDS FPS 60 SKYLINE 120ML,0,NaN
84,7896212479924,TYLENOL 200MG GOTAS 15ML,0,NaN
85,7891010249274,TYLENOL 750MG BLISTER C/4 CP,0,NaN
86,7896212422517,TYLENOL 750MG CARTUCHO C/ 20CP,0,NaN
87,7896212428861,TYLENOL BEBE GOTAS 15ML,0,NaN

In [ ]:
print(tabela)

              EAN                              Descrição  Preço  \
0   7891010504779                   BAND-AID TRANSP 10UN      0
1   7891010504755                   BAND-AID TRANSP 40UN      0
2   7891010668631        BAND-AID ULTRAPROT 24X15 UN BIL      0
3   7891010576509       CAREFREE PROTECAO C/PERFUME 80UN      0
4   7891010015268  CAREFREE PROTEÇÃO SEM FRAGRANCIA 15UN      0
..            ...                                    ...    ...
83  7891010026264      SUNDOWN KIDS FPS 60 SKYLINE 120ML      0
84  7896212479924               TYLENOL 200MG GOTAS 15ML      0
85  7891010249274           TYLENOL 750MG BLISTER C/4 CP      0
86  7896212422517         TYLENOL 750MG CARTUCHO C/ 20CP      0
87  7896212428861                TYLENOL BEBE GOTAS 15ML      0

    Estoque em Loja
0                 0
1                 0
2                 0
3                 0
4                 0
..              ...
83                0
84                0
85                0
86                0
87                0

[88 rows x 4 columns]

In [ ]:
tabela["Estoque em Loja"] = 0

In [ ]:
tabela.to_excel("Produtos_JJ.xlsx", index = False)